name: Run Tests

on:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy

    - name: Run tests
      run: python src/tests/run_tests.py | tee test_output.txt

    - name: Display clean test results
      run: cat test_output.txt
